{
 "title": "Course LLM Dashboard",
 "description": "LLM ZoomCamp",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Relevance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  relevance,\r\n  COUNT(*) as count\r\nFROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom()  AND  $__timeTo()\r\nGROUP BY relevance\r\nORDER BY count DESC "
    }
   ]
  },
  {
   "title": "ça coût $",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(openai_cost)\r\nFROM conversations"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  model_used,\r\n  COUNT(*) as count\r\nFROM conversations\r\nGROUP BY model_used"
    }
   ]
  },
  {
   "title": "Timestamp ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  response_time\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  question,\r\n  answer,\r\n  relevance\r\nFROM conversations\r\nORDER BY timestamp DESC\r\nLIMIT 8"
    }
   ]
  }
 ]
}